[book]
authors = ["userNanni"]
language = "pt-br"
multilingual = false
src = "src"
title = "Handbook de Planilhas"
[output.html]
mathjax-support = true
smart-punctuation = true
copy-fonts = true
additional-css = ["custom.css"]

